name: notes_on_english_literature

description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  # Flutter/Dart official packages
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

  # Firebase packages
  firebase_core: ^1.1.1
  cloud_firestore: ^2.1.0
  firebase_auth: ^1.1.4
  firebase_storage: ^8.0.6
  firebase_messaging: ^9.1.4

  # Google packages
  google_ml_kit: ^0.2.0
  google_fonts: ^2.0.0

  # objectbox packages
  objectbox: ^0.14.0
  objectbox_flutter_libs: ^0.14.0

  # statement packages
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0
  flutter_state_notifier: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono:

  build_runner: ^2.0.2
  json_serializable: ^4.1.1
  objectbox_generator: ^0.14.0

flutter:
  uses-material-design: true
  generate: true